org: deepaktammali
app: kibbitz-backend
service: api

frameworkVersion: '2'

configValidationMode: error

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    DATABASE_URI: 'sqlite::memory:'

plugins:
  - serverless-offline

functions:
  - ${file("./services/feed/functions.yml")}